// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

export const meta = {
  datasets: {
    count: { type: 'query' },
    deleteByCkanId: { type: 'mutation' },
    get: { type: 'query' },
    getByCkanId: { type: 'query' },
    list: { type: 'query' },
    upsert: { type: 'mutation' },
  },
  guests: {
    createNewGuest: { type: 'mutation' },
    getGuestBySessionId: { type: 'query' },
    guestExists: { type: 'query' },
  },
  resources: {
    count: { type: 'query' },
    deleteByDataset: { type: 'mutation' },
    get: { type: 'query' },
    getByCkanId: { type: 'query' },
    listByDataset: { type: 'query' },
    listByFormat: { type: 'query' },
    upsert: { type: 'mutation' },
  },
  threads: {
    deleteThread: { type: 'mutation' },
    getAuthResourceId: { type: 'query' },
    getThreadContextWindow: { type: 'query' },
    listUserThreads: { type: 'query' },
    listUserThreadsPaginated: { type: 'query' },
    renameThread: { type: 'mutation' },
    upsertThreadBilling: { type: 'mutation' },
    upsertThreadContext: { type: 'mutation' },
  },
  users: {
    getCurrentUser: { type: 'query' },
    updateThemePreference: { type: 'mutation' },
  },
  _http: {},
} as const;

export type Meta = typeof meta;
